#if defined _smlib_included
	#endinput
#endif
#define _smlib_included

#define SMLIB_VERSION "0.9.7"

#include "smlib/general.inc"

#include "smlib/arrays.inc"
#include "smlib/clients.inc"
#include "smlib/colors.inc"
#include "smlib/concommands.inc"
#include "smlib/convars.inc"
#include "smlib/crypt.inc"
#include "smlib/debug.inc"
#include "smlib/dynarrays.inc"
#include "smlib/edicts.inc"
#include "smlib/effects.inc"
#include "smlib/entities.inc"
#include "smlib/files.inc"
#include "smlib/game.inc"
#include "smlib/math.inc"
#include "smlib/menus.inc"
#include "smlib/server.inc"
#include "smlib/strings.inc"
#include "smlib/sql.inc"
#include "smlib/teams.inc"
#include "smlib/vehicles.inc"
#include "smlib/weapons.inc"
#include "smlib/world.inc"
